name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: 26.1.10909125
          cmake: 3.22.1

      - name: Restore dependencies
        run: dotnet restore GalaxyBudsClient.Android.csproj -p:IsAndroid=true

      - name: Build APK
        run: |
          dotnet publish GalaxyBudsClient.Android.csproj \
            -c Release \
            -p:IsAndroid=true \
            -p:AndroidSdkDirectory=$ANDROID_HOME \
            -p:AndroidPackageFormats=apk \
            -p:SupportedOSPlatformVersion=21 \
            -p:EmbedAssembliesIntoApk=true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: GalaxyBudsClient-Android
          path: '**/*.apk'
